### PR TITLE
Lambert72

### PR DESCRIPTION
**Pull request by ssg-hub**
Pleae check if the functions work correctly. The data from URL is not perfect hence tweaks might be needed.

### CODE REVIEW

**Comment by Pablousse** [comment]
on apisearch you need to remove the "from re import X" since your don't use regex in the page
also the first comment "# importing the requests library" you can delete it, everyone starts the file with the import so it doesn't need comment
The first line should be the first import so you can remove the empty line
You instanciate "URL_0 = "https://loc.geopunt.be/v1/location?" but never use it, so you can remove it
you instanciate "URL" on line 8 but you overide it on line 18 and 40, you should put the right url into the line 8 and remove the others
line 66 you should remove it
everything after line 83 are tests, it should be in a unit test file or removed but not in this file

**Comment by ssg-hub** [comment]
> on apisearch you need to remove the "from re import X" since your don't use regex in the page
> also the first comment "# importing the requests library" you can delete it, everyone starts the file with the import so it doesn't need comment
> The first line should be the first import so you can remove the empty line
> You instanciate "URL_0 = "https://loc.geopunt.be/v1/location?" but never use it, so you can remove it
> you instanciate "URL" on line 8 but you overide it on line 18 and 40, you should put the right url into the line 8 and remove the others
> line 66 you should remove it
> everything after line 83 are tests, it should be in a unit test file or removed but not in this file

@Pablousse....what if I want to tell the user there are 2 options of URLS they have. Make the user choose and pass it in the function as a parameter? that would overly complicate the function?

**Comment by arnaud** [comment]
@ssg-hub something tells me that your mention was not intended for me

**Comment by Pablousse** [comment]
@arnaud Hi, really sorry about it, it's a learning project, we'll make our best not to disturb you again

**Comment by ssg-hub** [comment]
> @ssg-hub something tells me that your mention was not intended for me

Kindly ignore Arnaud

**Pull request closed without merging**
